version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: back/Dockerfile
      args:
        DB_URL: ${DB_URL}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
    environment:
        DB_URL: ${DB_URL}
        DB_PASSWORD: ${DB_PASSWORD}
        DB_USERNAME: ${DB_USERNAME}
    ports:
      - "8080:8080"
  front:
    build:
      context: .
      dockerfile: front/Dockerfile
    ports:
      - "3000:3000"
    restart: always
    depends_on:
      - backend

  prometheus:
    image: prom/prometheus
    volumes:
      - ./config/:/etc/prometheus/
      - prometheus_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
      - '--storage.tsdb.path=/prometheus'
    ports:
      - "9090:9090"
    depends_on:
      - backend
    restart: always

  redis:
    image: redis
    ports:
      - "6379:6379"
    # restart: always

volumes:
  prometheus_data: {}
